name: Pull Request

on:
  pull_request:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: npm
      - run: npm install
      - run: npm run lint
      - run: npm test
